version: "3"
services:
   web:
     #定义主机名
     container_name: mynginx
     #使用的镜像
     image: nginx:latest
     #容器的映射端口
     ports:
       - 8080:80
     #定义挂载点         
     volumes:
       - ./html:/usr/share/nginx/html
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./conf.d:/etc/nginx/conf.d
       - ./logs:/var/log/nginx
     #docker 重启后，容器自启动
     restart: always
     # 打开标准输入，可以接受外部输入
     stdin_open: true
     # 伪终端
     tty: true